//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products:IEntityBase
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int stocks { get; set; }
        public decimal Price { get; set; }
        public int categoryId { get; set; }
        public string productCode { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
